bag_dir: "/home/ubuntu/dataset/rosbags/pekori"
output_dir: "/home/ubuntu/dataset/lerobot_dataset/cube_grasp_enhanced"
config: "configs/crane_features.py"
target_freq: 20
# Static frame filtering configuration
filter_static: true # 静止フレーム除外を有効にする
joint_threshold: 0.001 # 関節の変化量閾値（ラジアン）
gripper_threshold: 0.001 # グリッパーの変化量閾値
# Grip frame amplification configuration
enable_grip_amplification: true # グリップフレーム増幅を有効にする
grip_amplification_factor: 50 # グリップフレームの増幅倍率
grip_window_size: 5 # グリップポイント前後のフレーム数
